#include "Game/SelectGameMode.h"
#include "SelectGameState.h"
#include "WEnumFile.h"
#include "WGameInstance.h"
#include "GameFramework/PlayerState.h"


ASelectGameMode::ASelectGameMode()
{
	if (!HasAuthority()) // í´ë¼ì´ì–¸íŠ¸ê°€ GameModeë¥¼ ìƒì„±í•˜ì§€ ëª»í•˜ë„ë¡ ì œí•œ
	{
		Destroy();
	}
}

void ASelectGameMode::BeginPlay()
{
	Super::BeginPlay();
	UE_LOG(LogTemp, Log, TEXT("GameMode BeginPlay!"));
	ASelectGameState* SelectGameState = Cast<ASelectGameState>(GetWorld()->GetGameState());
	if (SelectGameState != nullptr)
	{
		UE_LOG(LogTemp, Log, TEXT("GameMode GameState ì°¸ì¡°!"));
		SelectGS = SelectGameState;
	}
	
	GetWorld()->GetTimerManager().SetTimer(DecreaseTimerHandle, this, &ThisClass::DecreaseTimer, 1.0f, true);

	LoadPlayerTeamsFromGameInstance();
}

void ASelectGameMode::LoadPlayerTeamsFromGameInstance()
{
	UWGameInstance* WGI = Cast<UWGameInstance>(GetGameInstance());
	if (WGI)
	{
		TMap<FString, E_TeamID> LoadedMap = WGI->GetSavedTeam();
		for (auto& It : LoadedMap)
		{
			FString PlayerName = It.Key;
			E_TeamID TeamID = It.Value;
			if (!PlayerName.IsEmpty())
			{
				SelectPlayerReadyStatus.Add(PlayerName, FPlayerValue(TeamID, false,nullptr));
				UE_LOG(LogTemp, Log, TEXT("ğŸ”¹ ë¶ˆëŸ¬ì˜¨ PlayerController: %s, TeamID: %d"), *PlayerName, TeamID);
			}
		}
	}
}

void ASelectGameMode::UpdateCharName(int32 MWidgetID, FText MCharName)
{
	UE_LOG(LogTemp, Log, TEXT("GameModeUpdateCharName"));

	SelectGS->M_UpdateCharName(MWidgetID, MCharName);
}

void ASelectGameMode::SetTeamSlotIsChecked(int32 TeamID, int32 UncheckTeamID, FText UserNickName)
{
	GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Blue, TEXT("GameModeSetTeamSlotIsChecked"));
	if (UncheckTeamID == 0)
	{
		SelectGS->M_UpdateTeamSlot(TeamID, UserNickName);
	}
	else
	{
		SelectGS->M_UnCheckTeamSlot(UncheckTeamID);
		SelectGS->M_UpdateTeamSlot(TeamID, UserNickName);	
	}
}

void ASelectGameMode::SetUserData(int32 MWidgetID, FText MUserNickName)
{
	UE_LOG(LogTemp, Log, TEXT("GameModeSetUserData!"));
}

void ASelectGameMode::DecreaseTimer()
{
	UE_LOG(LogTemp, Log, TEXT("GameModeDecreaseTimer()"));

	SelectGS->SelectTime--;
}

void ASelectGameMode::SetIsReady(APlayerController* PlayerController,E_TeamID TeamVal, bool bReady, TSubclassOf<APawn> PawnClass)
{
	GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Blue, TEXT("SetPlayerReady is called"));
	if (!PlayerController)
	{
		return;
	}
	
	FString PlayerName = PlayerController->PlayerState->GetPlayerName();
	
	FPlayerValue* Value = SelectPlayerReadyStatus.Find(PlayerName);
	
	if (Value)
	{
		Value->TeamValue = TeamVal;
		Value->IsReady = bReady;
		Value->WPawnClass = PawnClass;
		
		UE_LOG(LogTemp, Log, TEXT("SelectPlayerReadyStatus ì°¾ì•˜ìŒ!, %d"),bReady);
	}
	else
	{
		UE_LOG(LogTemp, Log, TEXT("SelectPlayerReadyStatus ìƒˆë¡œ ì¶”ê°€!"));
		SelectPlayerReadyStatus.Add(PlayerName, FPlayerValue(TeamVal, bReady, PawnClass));
	}
}

void ASelectGameMode::CheckMatch()//ë§¤ì¹˜ ì‹œì‘
{
	if (AreAllPlayersReady())
	{
		UE_LOG(LogTemp, Log, TEXT("AllPlayersReady"));
		if (AreTeambalanced())
		{
			UE_LOG(LogTemp, Log, TEXT("Matchisbalanced"));
			SaveMatchPlayersToGameInstance();
		}
		else
		{
			ReturnToMainMenu();
		}
	}
	else
	{
		ReturnToMainMenu();
	}
}

bool ASelectGameMode::AreAllPlayersReady()
{
	for (auto It = SelectPlayerReadyStatus.CreateIterator(); It; ++It)
	{
		if (It->Key.IsEmpty()) // í”Œë ˆì´ì–´ê°€ ë– ë‚¬ë‹¤ë©´ ì œê±°
		{
			UE_LOG(LogTemp, Log, TEXT("Key ì—†ìŒ!, %s"),*It->Key);
			return false;
		}

		if (!It->Value.IsReady) // ì•„ì§ ì¤€ë¹„ë˜ì§€ ì•Šì€ í”Œë ˆì´ì–´ê°€ ìˆìœ¼ë©´ ë¦¬í„´
		{
			UE_LOG(LogTemp, Log, TEXT("ì¤€ë¹„ê°€ ë˜ì§€ì•Šì•˜ìŒ!, %s %d"),*It->Key,It->Value.IsReady);
			return false;
		}
	}
	return true; // ëª¨ë“  í”Œë ˆì´ì–´ê°€ ì¤€ë¹„ ì™„ë£Œë¨
}

bool ASelectGameMode::AreTeambalanced()
{
	int32 BlueTeamCount= 0;
	int32 RedTeamCount= 0;
	
	for (auto It = SelectPlayerReadyStatus.CreateIterator(); It; ++It)
	{
		if (It->Value.TeamValue==E_TeamID::Blue)
		{
			BlueTeamCount++;
		}
		else if (It->Value.TeamValue==E_TeamID::Red)
		{
			RedTeamCount++;
		}
	}
	
	if (RedTeamCount != 0 && BlueTeamCount != 0 && BlueTeamCount == RedTeamCount)
	{
		return true;
	}
	else return false;
}

void ASelectGameMode::SaveMatchPlayersToGameInstance()
{
	UWGameInstance* WGI = Cast<UWGameInstance>(GetGameInstance());
	if (WGI)
	{
		for (auto& It : SelectPlayerReadyStatus)
		{
			FString PlayerName = It.Key;
			if (!PlayerName.IsEmpty())
			{
				UE_LOG(LogTemp, Log, TEXT("SaveMatchPlayerTeam!"));
				WGI->SaveMatchPlayerTeam(It.Key, It.Value.TeamValue, It.Value.WPawnClass );
			}
		}
	}
	
	MapTranslate();
}

void ASelectGameMode::ReturnToMainMenu()
{
	if (MainMenuMap.IsNull())
	{
		UE_LOG(LogTemp, Warning, TEXT("MainMenuMap is not set in GameMode!"));
		return;
	}
		
	FString MainMap = MainMenuMap.GetAssetName();
		
	GetWorld()->ServerTravel(MainMap);
}

void ASelectGameMode::MapTranslate()
{
	if (WGameMap.IsNull())
	{
		UE_LOG(LogTemp, Warning, TEXT("SelectMap is not set in GameMode!"));
		return;
	}
	
	FString NextMap = WGameMap.GetAssetName();
	
	GetWorld()->ServerTravel(NextMap);
}
